hp() {
	local max32bit=4294967295
	local h=$(jot -r 1 5 $max32bit)
	local d=$(jot -r 1 0 65365)
	hm=$((h + d))
	if [ $hm -gt $max32bit ]; then
		hm=$max32bit
	fi
	echo "$h-$hm"
}

check_h_overlap()
{
	h=$1
	ha=${h%%-*}
	hb=${h#*-}
	shift
	for i in "$@"; do
		ia=${i%%-*}
		ib=${i#*-}

		if [ $hb -ge $ia ] && [ $ib -ge $ha ]; then
			return 1
		fi
	done
	return 0
}

# Actual confiruration parameters for AWG (AWG2)
awg_config() {
	for i in 1 2 3 4; do
		jc=$(jot -r 1 3 10)
		jmin=$(jot -r 1 50 100)
		jmax=$(jot -r 1 $jmin 1000)

		s1=$(jot -r 1 15 1132)
		s2=$(jot -r 1 15 1188)
		s3=$(jot -r 1 15 800)
		s4=$(jot -r 1 15 100)

		h1=$(hp)
		h2=$(hp)
		h3=$(hp)
		h4=$(hp)

		# check s1 + 56 == s2
		[ $(($s1 + 56)) -eq $s2 ] && continue

		# check overlaps
		check_h_overlap $h1 $h2 $h3 $h4 || continue
		check_h_overlap $h2 $h1 $h3 $h4 || continue
		check_h_overlap $h3 $h1 $h2 $h4 || continue
		check_h_overlap $h4 $h1 $h2 $h3 || continue

		break
	done

	cfg="jc $jc jmin $jmin jmax $jmax
		s1 $s1 s2 $s2 s3 $s3 s4 $s4
		h1 $h1 h2 $h2 h3 $h3 h4 $h4"

	echo $cfg
	echo $cfg 1>&2
}

# Compatibility confiruration parameters for AWG (AWG1)
awg1_config() {
	for i in 1 2 3 4; do
		jc=$(jot -r 1 3 10)
		jmin=$(jot -r 1 50 100)
		jmax=$(jot -r 1 $jmin 1000)

		s1=$(jot -r 1 15 1132)
		s2=$(jot -r 1 15 1188)

		h1=$(jot -r 1 5 4294967295)
		h2=$(jot -r 1 5 4294967295)
		h3=$(jot -r 1 5 4294967295)
		h4=$(jot -r 1 5 4294967295)

		if [ $(($s1 + 56)) -ne $s2 ] && \
		   [ $(echo -e "$h1\n$h2\n$h3\n$h4" | sort -u | wc -l) -eq 4 ]; then
			break
		fi
	done

	echo \
		jc $jc jmin $jmin jmax $jmax \
		s1 $s1 s2 $s2 \
		h1 $h1 h2 $h2 h3 $h3 h4 $h4
}

setup_vnet_jails() {
	local endpoint1=$1 endpoint2=$2
	local epair1 epair2

	kldload -n if_wg || atf_skip "This test requires if_wg and could not load it"
	kldload -n if_bridge || atf_skip "This test requires if_bridge and could not load it"

	jail -r wgtest1 2> /dev/null || true
	jail -r wgtest2 2> /dev/null || true

	epair1=$(vnet_mkepair)
	epair2=$(vnet_mkepair)

	vnet_init

	vnet_mkjail wgtest1 ${epair1}b
	vnet_mkjail wgtest2 ${epair2}b

	ifconfig wgbr0 > /dev/null 2>&1 || ifconfig bridge create name wgbr0
	for i in $(ifconfig wgbr0 | awk '/member:/ {print $2}'); do
		ifconfig wgbr0 deletem $i
	done
	ifconfig wgbr0 up

	jexec wgtest1 ifconfig ${epair1}b ${endpoint1}/24 up
	jexec wgtest2 ifconfig ${epair2}b ${endpoint2}/24 up

	ifconfig ${epair1}a up
	ifconfig ${epair2}a up
	ifconfig wgbr0 addm ${epair1}a addm ${epair2}a
}

setup_debug() {
	case "$DEBUG" in
		yes|true|1)
			exec > `tty` 2>&1
			set -x
			;;
	esac
}
